services:
  frontend-dev:
    env_file: ".env"
    container_name: "frontend-dev"
    environment:
      - HOSTNAME=${HOSTNAME}
    build:
      context: ./frontend
      target: builder
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - backend-dev
    volumes:
      - ./frontend:/app
      - ./certs:/app/certs:ro
      - /app/node_modules

  backend-dev:
    env_file: ".env"
    container_name: "backend-dev"
    build:
      context: ./backend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./certs:/app/certs:ro
    environment:
      - NODE_ENV=development
    command: ["sh", "./entrypoint.sh"]

  frontend-prod:
    env_file: ".env"
    container_name: "frontend-prod"
    build:
      context: ./frontend
      target: production
    ports:
      - "5173:5173"
    depends_on:
      - backend-prod
    volumes:
      - ./certs:/app/certs:ro
      - ./frontend/mime.types:/etc/nginx/mime.types:ro

  backend-prod:
    env_file: ".env"
    container_name: "backend-prod"
    build:
      context: ./backend
      target: production
    volumes:
      - ./certs:/app/certs:ro
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
