services:
  frontend-dev:
    env_file: ".env"
    environment:
      - HOSTNAME=${HOSTNAME}
    build:
      context: ./frontend
      target: builder
    container_name: frontend
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - backend-dev
    volumes:
      - ./frontend:/app
      - ./certs:/app/certs:ro
      - /app/node_modules

  backend-dev:
    env_file: ".env"
    build:
      context: ./backend
      target: development
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./certs:/app/certs:ro
    environment:
      - NODE_ENV=development
    command: npm run dev


  frontend-prod:
    env_file: ".env"
    build:
      context: ./frontend
      target: production
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend-prod
    volumes:
      - /usr/share/nginx/html
      - ./certs:/app/certs:ro


  backend-prod:
    env_file: ".env"
    build:
      context: ./backend
      target: production
    container_name: backend
    volumes:
      - ./certs:/app/certs:ro
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm start
