services:
  frontend-dev:
    env_file: ".env"
    build:
      context: ./frontend
      target: builder
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - backend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend-dev:
    env_file: ".env"
    build:
      context: ./backend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["sh", "./entrypoint.sh"]

  frontend-prod:
    env_file: ".env"
    build:
      context: ./frontend
      target: production
    ports:
      - "80:80"
    depends_on:
      - backend-prod
    volumes:
      - /usr/share/nginx/html

  backend-prod:
    env_file: ".env"
    build:
      context: ./backend
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # 👇 Pas besoin de `command`, le Dockerfile fait le boulot
